[package]
name = "ccc"
version = "0.1.0"
edition = "2024"

[dependencies]
jiff = "0.2.16"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
spinoff = "0.8.0"
ureq = { version = "3.1.4", features = ["json"]}
